name: Manual Start

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'    
          

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: "Dinge anzeigen"
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
    
      - name: "Anzeigen von standard Evironment"
        run: | 
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"
          
        
      
          
