name: Manual Start

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'    
          

jobs:
  displays:
    runs-on: ubuntu-latest
    env:
      LEVEL: ${{ inputs.logLevel }}
      TAGS: ${{ inputs.tags }}
      ENVIRONMENT: ${{ inputs.environment }}
          
    steps:
      - name: Dinge anzeigen
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
           
      - name: Anzeigen von standard Environment Variablen
        run: | 
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"
          
        
      
          
